language: objective-c
osx_image: xcode10

xcode_workspace: Example/Leanplum-SDK.xcworkspace
xcode_scheme: Leanplum-SDK-Example
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example

before_deploy:
- ./build.sh

deploy:
  - provider: script
    script: ./Tools/push.sh
    on:
      tags: true
  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: Leanplum.framework.zip
    skip_cleanup: true
    draft: true
    on:
      tags: true

